### PR TITLE
Use more than two AZs / VPC subnets / ELBs per ASG

### PR DESCRIPTION
**Pull request by chiefy**
- Changed `load_balancer_name` to `load_balancer_names` input can be a CSV
- Changed `az1, az2..` to `availability_zones` input can be a CSV
- Changed `subnet_az1, subnet_az2..` to `vpc_zone_subnets` input can be a CSV
- Added `.editorconfig`
- Tightened up comment formatting
- Added full example

### CODE REVIEW

**Comment by chiefy** [comment]
:crickets:

Anyone?

**Comment by mtb-xt** [comment]
Can this be merged? :thumbsup:

**Comment by tamsky** [comment]
LGTM :+1:

**Comment by chiefy** [comment]
paging @phinze @sethvargo @solarce ^

**Comment by phinze** [comment]
Sorry for the delay. This looks great - thanks for this, @chiefy!

**Comment by phinze** [comment]
@chiefy BTW ping us back if you're interested in being invited to the org as a collaborator - as you can see we could use some more folks around here! :grin:

**Pull request merged**
